"""add_granular_permissions

Revision ID: 2ce1fa430da8
Revises: 014_add_chatbot_activities
Create Date: 2026-01-06 16:41:19.646224

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ce1fa430da8'
down_revision: Union[str, None] = '014_add_chatbot_activities'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('chat_messages_session_id_fkey'), 'chat_messages', type_='foreignkey')
    op.create_foreign_key(None, 'chat_messages', 'chat_sessions', ['session_id'], ['id'])
    op.drop_constraint(op.f('chat_sessions_chatbot_id_fkey'), 'chat_sessions', type_='foreignkey')
    op.create_foreign_key(None, 'chat_sessions', 'chatbots', ['chatbot_id'], ['id'])
    op.drop_constraint(op.f('chatbot_appearances_chatbot_id_key'), 'chatbot_appearances', type_='unique')
    op.drop_constraint(op.f('chatbot_appearances_chatbot_id_fkey'), 'chatbot_appearances', type_='foreignkey')
    op.create_foreign_key(None, 'chatbot_appearances', 'chatbots', ['chatbot_id'], ['id'])
    op.add_column('chatbot_permissions', sa.Column('can_manage_knowledge', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('chatbot_permissions', sa.Column('can_manage_appearance', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('chatbot_permissions', sa.Column('can_resolve_queries', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('chatbot_permissions', sa.Column('can_view_analytics', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    
    # Update existing permissions based on level
    op.execute("UPDATE chatbot_permissions SET can_manage_knowledge = true, can_manage_appearance = true, can_resolve_queries = true, can_view_analytics = true WHERE permission_level::text IN ('owner', 'admin')")
    op.execute("UPDATE chatbot_permissions SET can_manage_knowledge = true, can_resolve_queries = true, can_view_analytics = true WHERE permission_level::text = 'editor'")

    op.alter_column('chatbot_permissions', 'chatbot_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.create_unique_constraint('uq_user_chatbot', 'chatbot_permissions', ['user_id', 'chatbot_id'])
    op.drop_column('chatbots', 'description')
    op.drop_column('chatbots', 'is_active')
    op.drop_constraint(op.f('crawl_history_knowledge_source_id_fkey'), 'crawl_history', type_='foreignkey')
    op.create_foreign_key(None, 'crawl_history', 'knowledge_sources', ['knowledge_source_id'], ['id'])
    op.drop_constraint(op.f('crawl_schedules_knowledge_source_id_fkey'), 'crawl_schedules', type_='foreignkey')
    op.create_foreign_key(None, 'crawl_schedules', 'knowledge_sources', ['knowledge_source_id'], ['id'])
    op.drop_constraint(op.f('crawled_pages_knowledge_source_id_fkey'), 'crawled_pages', type_='foreignkey')
    op.create_foreign_key(None, 'crawled_pages', 'knowledge_sources', ['knowledge_source_id'], ['id'])
    op.drop_constraint(op.f('embeddings_knowledge_source_id_fkey'), 'embeddings', type_='foreignkey')
    op.drop_constraint(op.f('embeddings_chatbot_id_fkey'), 'embeddings', type_='foreignkey')
    op.create_foreign_key(None, 'embeddings', 'knowledge_sources', ['knowledge_source_id'], ['id'])
    op.create_foreign_key(None, 'embeddings', 'chatbots', ['chatbot_id'], ['id'])
    op.drop_constraint(op.f('knowledge_sources_chatbot_id_fkey'), 'knowledge_sources', type_='foreignkey')
    op.create_foreign_key(None, 'knowledge_sources', 'chatbots', ['chatbot_id'], ['id'])
    op.drop_constraint(op.f('qa_pairs_knowledge_source_id_fkey'), 'qa_pairs', type_='foreignkey')
    op.create_foreign_key(None, 'qa_pairs', 'knowledge_sources', ['knowledge_source_id'], ['id'])
    op.drop_constraint(op.f('uploaded_files_knowledge_source_id_fkey'), 'uploaded_files', type_='foreignkey')
    op.create_foreign_key(None, 'uploaded_files', 'knowledge_sources', ['knowledge_source_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'uploaded_files', type_='foreignkey')
    op.create_foreign_key(op.f('uploaded_files_knowledge_source_id_fkey'), 'uploaded_files', 'knowledge_sources', ['knowledge_source_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'qa_pairs', type_='foreignkey')
    op.create_foreign_key(op.f('qa_pairs_knowledge_source_id_fkey'), 'qa_pairs', 'knowledge_sources', ['knowledge_source_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'knowledge_sources', type_='foreignkey')
    op.create_foreign_key(op.f('knowledge_sources_chatbot_id_fkey'), 'knowledge_sources', 'chatbots', ['chatbot_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'embeddings', type_='foreignkey')
    op.drop_constraint(None, 'embeddings', type_='foreignkey')
    op.create_foreign_key(op.f('embeddings_chatbot_id_fkey'), 'embeddings', 'chatbots', ['chatbot_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('embeddings_knowledge_source_id_fkey'), 'embeddings', 'knowledge_sources', ['knowledge_source_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'crawled_pages', type_='foreignkey')
    op.create_foreign_key(op.f('crawled_pages_knowledge_source_id_fkey'), 'crawled_pages', 'knowledge_sources', ['knowledge_source_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'crawl_schedules', type_='foreignkey')
    op.create_foreign_key(op.f('crawl_schedules_knowledge_source_id_fkey'), 'crawl_schedules', 'knowledge_sources', ['knowledge_source_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'crawl_history', type_='foreignkey')
    op.create_foreign_key(op.f('crawl_history_knowledge_source_id_fkey'), 'crawl_history', 'knowledge_sources', ['knowledge_source_id'], ['id'], ondelete='CASCADE')
    op.add_column('chatbots', sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False))
    op.add_column('chatbots', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_constraint('uq_user_chatbot', 'chatbot_permissions', type_='unique')
    op.alter_column('chatbot_permissions', 'chatbot_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_column('chatbot_permissions', 'can_view_analytics')
    op.drop_column('chatbot_permissions', 'can_resolve_queries')
    op.drop_column('chatbot_permissions', 'can_manage_appearance')
    op.drop_column('chatbot_permissions', 'can_manage_knowledge')
    op.drop_constraint(None, 'chatbot_appearances', type_='foreignkey')
    op.create_foreign_key(op.f('chatbot_appearances_chatbot_id_fkey'), 'chatbot_appearances', 'chatbots', ['chatbot_id'], ['id'], ondelete='CASCADE')
    op.create_unique_constraint(op.f('chatbot_appearances_chatbot_id_key'), 'chatbot_appearances', ['chatbot_id'], postgresql_nulls_not_distinct=False)
    op.drop_constraint(None, 'chat_sessions', type_='foreignkey')
    op.create_foreign_key(op.f('chat_sessions_chatbot_id_fkey'), 'chat_sessions', 'chatbots', ['chatbot_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'chat_messages', type_='foreignkey')
    op.create_foreign_key(op.f('chat_messages_session_id_fkey'), 'chat_messages', 'chat_sessions', ['session_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###

