"""check for missing changes

Revision ID: a77edd5faba9
Revises: 016_add_is_preview_session
Create Date: 2026-01-09 11:26:51.003493

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a77edd5faba9'
down_revision: Union[str, None] = '016_add_is_preview_session'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('chatbot_activities_chatbot_id_fkey'), 'chatbot_activities', type_='foreignkey')
    op.create_foreign_key(None, 'chatbot_activities', 'chatbots', ['chatbot_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chatbot_activities', type_='foreignkey')
    op.create_foreign_key(op.f('chatbot_activities_chatbot_id_fkey'), 'chatbot_activities', 'chatbots', ['chatbot_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###

